import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  currentFeelingCard: {
    backgroundColor: "#E8F5E9",
    borderRadius: 16,
    margin: 16,
    padding: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  currentLocationText: {
    fontSize: 16,
    color: "#4CAF50",
    fontWeight: "bold",
    marginBottom: 6,
  },
  feelingSummary: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  summaryText: {
    fontSize: 20,
    fontWeight: "bold",
    marginLeft: 10,
    color: "#333",
  },
  mainTagText: {
    fontSize: 16,
    color: "#388E3C",
    fontWeight: "bold",
    marginBottom: 10,
  },
  postButton: {
    marginTop: 10,
    padding: 14,
    backgroundColor: "#4CAF50",
    borderRadius: 30,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
    width: "100%",
  },
  postButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  section: {
    marginHorizontal: 16,
    marginTop: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 10,
  },
  featuredTopicCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 1,
  },
  featuredTopicImage: {
    width: 80,
    height: 60,
    borderRadius: 8,
    marginRight: 12,
  },
  featuredTopicTextContainer: {
    flex: 1,
  },
  featuredTopicTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#388E3C",
    marginBottom: 4,
  },
  featuredTopicDescription: {
    fontSize: 14,
    color: "#666",
  },
  postCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    flexDirection: "row",
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 1,
  },
  postImage: {
    width: 90,
    height: 70,
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
  },
  postContent: {
    flex: 1,
    padding: 10,
    justifyContent: "center",
  },
  postUser: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#4CAF50",
    marginBottom: 2,
  },
  postFeeling: {
    fontSize: 14,
    color: "#333",
    marginBottom: 4,
  },
  postTags: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 4,
  },
  tagText: {
    fontSize: 12,
    color: "#388E3C",
    backgroundColor: "#E8F5E9",
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginRight: 4,
    marginBottom: 2,
  },
  postActions: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 2,
  },
  likesText: {
    fontSize: 12,
    color: "gray",
    marginLeft: 4,
  },
});

export default styles;