// styles/MapScreenStyles.js
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f0f2f5",
  },
  mapContainer: {
    flex: 1,
    backgroundColor: "#e0e0e0",
    justifyContent: "center",
    alignItems: "center",
  },
  map: {
    width: "100%",
    height: "100%",
  },
  loadingText: {
    fontSize: 18,
    color: "#666",
  },
  errorText: {
    fontSize: 16,
    color: "red",
    textAlign: "center",
    padding: 20,
  },
  // 投稿ボタン
  postGeoLogButton: {
    position: "absolute",
    left: 20,
    backgroundColor: "#4CAF50",
    borderRadius: 30,
    width: 60,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 8,
  },
  // ヒートマップ切り替えボタン
  toggleHeatmapButton: {
    position: "absolute",
    right: 20,
    backgroundColor: "#fff",
    borderRadius: 30,
    width: 60,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 8,
  },
  // ボトムシート
  bottomSheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 8,
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
  },
  sheetHeader: {
    width: "100%",
    alignItems: "center",
    paddingTop: 10,
    backgroundColor: "#fff",
  },
  handleIndicator: {
    width: 40,
    height: 5,
    backgroundColor: "#ccc",
    borderRadius: 2.5,
    marginBottom: 10,
  },
  listContent: {
    flex: 1,
    paddingHorizontal: 10,
  },
  nearbyTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#333",
  },
  nearbyGeoLogCard: {
    flexDirection: "row",
    backgroundColor: "#fff",
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 3,
  },
  nearbyGeoLogEmoji: {
    fontSize: 24,
    marginRight: 10,
  },
  nearbyGeoLogContent: {
    flex: 1,
  },
  nearbyGeoLogLocation: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
  },
  nearbyGeoLogFeeling: {
    fontSize: 14,
    color: "#666",
    marginTop: 2,
  },
  // 投稿フィールド
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    zIndex: 99,
  },
  postFieldContainer: {
    position: "absolute",
    left: 30,
    right: 30,
    top: "15%",
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 10,
    zIndex: 100,
  },
  postFieldTitle: {
    fontWeight: "bold",
    fontSize: 18,
    marginBottom: 15,
    textAlign: "center",
  },
  emotionSelector: {
    flexDirection: "row",
    marginBottom: 15,
  },
  emotionButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 4,
  },
  selectedEmotionButton: {
    borderWidth: 2,
    borderColor: "#4CAF50",
    transform: [{ scale: 1.2 }],
  },
  emotionButtonText: {
    fontSize: 20,
  },
  postTextInput: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    padding: 10,
    minHeight: 80,
    marginBottom: 15,
    fontSize: 16,
    backgroundColor: "#fafafa",
  },
  photoButton: {
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
    borderWidth: 1,
    borderColor: "#4CAF50",
    borderRadius: 8,
    marginBottom: 15,
    backgroundColor: "#E8F5E9",
    justifyContent: "center",
  },
  photoButtonText: {
    marginLeft: 8,
    color: "#4CAF50",
  },
  postActionButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  postActionButton: {
    flex: 1,
    alignItems: "center",
    padding: 12,
    borderRadius: 8,
  },
  // マーカー
  emotionMarker: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 3,
  },
  emotionEmoji: {
    fontSize: 20,
  },
});

export default styles;